services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chatanalytics
      MYSQL_DATABASE: chatanalytics
#  spark:
#    image: docker.io/bitnamilegacy/spark:latest
#    environment:
#      - SPARK_MODE=master
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
#    ports:
#      - '8090:8080'
#      - '7077:7077'
#    volumes:
#      - './target/scala-2.13/chat-analytics-assembly-1.0.0-SNAPSHOT.jar:/opt/bitnami/spark/ivy/chat-analytics-assembly-1.0.0-SNAPSHOT.jar'
#      - './jars_dir:/opt/bitnami/spark/ivy:z'
#
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#  spark-worker:
#    image: docker.io/bitnamilegacy/spark:latest
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=1
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
#    volumes:
#      - './target/scala-2.13/chat-analytics-assembly-1.0.0-SNAPSHOT.jar:/opt/bitnami/spark/ivy/chat-analytics-assembly-1.0.0-SNAPSHOT.jar'
#      - './jars_dir:/opt/bitnami/spark/ivy:z'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"